### ISSUE TITLE
Cálculo sobre todos os dias

### ISSUE THREAD

**Issue by matheusnunes** [pcesarteixeira/HoursToLeaveSecullum#1]
Atualmente calcula apenas o dia de hoje.

Seria legal calcular todos eles.

Arruma isso ae

**Comment by pcesarteixeira** [comment]
Complementado a feature.
![Demo](https://user-images.githubusercontent.com/4458074/40583660-8e63c124-6169-11e8-8f7c-ce47ac133651.png)

**Comment by pcesarteixeira** [comment]
Feature implementada.
![captura de tela 2018-05-27 as 04 50 24](https://user-images.githubusercontent.com/4458074/40583952-12bac846-616f-11e8-86b4-a86f90ba8f49.png)

**Comment by matheusnunes** [comment]
É UMA LENDA!
