### ISSUE TITLE
Na minha máquina não funciona

### ISSUE THREAD

**Issue by maiconsansonrc** [pcesarteixeira/HoursToLeaveSecullum#2]
ôoooo, Paulera.
Fui eu, todo facero, tentar executar no console e não rolou.
Segue o print:

![undefined](https://user-images.githubusercontent.com/24651814/40511846-66b70404-5f77-11e8-9c85-e3fc164aecdb.png)

**Comment by matheusnunes** [comment]
[UP]

**Comment by chisenberg** [comment]
[UP]

**Comment by thiagocalheiros** [comment]
na minha maquina apresenta o mesmo erro. (up)

**Comment by pcesarteixeira** [comment]
Problema resolvido na versão [v0.1.0-alpha](https://github.com/pcesarteixeira/HoursToLeaveSecullum/releases/tag/v0.1.0-alpha)
