### ISSUE TITLE
Na minha máquina não funciona v2

### ISSUE THREAD

**Issue by maiconsansonrc** [pcesarteixeira/HoursToLeaveSecullum#4]
Cada vez melhor, Paulete! **Instalei a extensão** no Chrome mas, em alguns dias, o horário de saída não aparece. Segue o print:

![image](https://user-images.githubusercontent.com/24651814/40623722-b8078928-627e-11e8-8db3-107a1a54a67c.png)

**Comment by thiagocalheiros** [comment]
@maiconsansonrc na minha não funcionava tb, mas a versão que saiu hoje ta 100%

**Comment by maiconsansonrc** [comment]
Paulete mostrando o poder da roça, o valor de beber o leite da vaca direto da teta. Que orgulho, que meu pai abençoe a todos!

**Comment by pcesarteixeira** [comment]
Fiz umas melhorias e tirei os 'invalid date' que aparecia nos dias futuros, porém só está funcionando para navegadores que estejam com o idioma Português setado como default. Logo mais faço uma correção disso.
